
name: bancher
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

fonts:
  family: Anton
  fonts:
    asset: fonts/Anton-Regular.ttf
    style: bold

flutter:

  uses-material-design: true
